"""Sync schema to models.py state after migration 003.

Auto-generated by scripts/diff_migration.py — review before applying.
Safe to run multiple times (ADD COLUMN IF NOT EXISTS, CREATE TABLE IF NOT EXISTS).

Revision ID: 004_schema_sync
Revises: 003_seed_data
Create Date: 2026-03-10
"""
from alembic import op
from sqlalchemy import text

revision = "004_schema_sync"
down_revision = "003_seed_data"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    # ── Formalizing runtime-only columns (from main.py _add_columns) ─
    # --- batches ---
    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'batches') THEN
                ALTER TABLE batches ADD COLUMN IF NOT EXISTS firing_profile_id UUID;
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'batches') THEN
                ALTER TABLE batches ADD COLUMN IF NOT EXISTS target_temperature INTEGER;
            END IF;
        END $$
    """))

    # --- colors ---
    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'colors') THEN
                ALTER TABLE colors ADD COLUMN IF NOT EXISTS is_basic BOOLEAN NOT NULL DEFAULT FALSE;
            END IF;
        END $$
    """))

    # --- factories ---
    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'factories') THEN
                ALTER TABLE factories ADD COLUMN IF NOT EXISTS served_locations JSONB;
            END IF;
        END $$
    """))

    # --- order_positions ---
    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'order_positions') THEN
                ALTER TABLE order_positions ADD COLUMN IF NOT EXISTS firing_round INTEGER NOT NULL DEFAULT 1;
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'order_positions') THEN
                ALTER TABLE order_positions ADD COLUMN IF NOT EXISTS quantity_sqm NUMERIC(10,3);
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'order_positions') THEN
                ALTER TABLE order_positions ADD COLUMN IF NOT EXISTS color_2 VARCHAR(200);
            END IF;
        END $$
    """))

    # --- production_order_items ---
    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_order_items') THEN
                ALTER TABLE production_order_items ADD COLUMN IF NOT EXISTS color_2 VARCHAR(100);
            END IF;
        END $$
    """))

    # --- production_orders ---
    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_orders') THEN
                ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ;
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_orders') THEN
                ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS sales_manager_contact VARCHAR(300);
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_orders') THEN
                ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS cancellation_requested BOOLEAN NOT NULL DEFAULT FALSE;
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_orders') THEN
                ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS cancellation_requested_at TIMESTAMPTZ;
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_orders') THEN
                ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS cancellation_decision VARCHAR(20);
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_orders') THEN
                ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS cancellation_decided_at TIMESTAMPTZ;
            END IF;
        END $$
    """))

    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'production_orders') THEN
                ALTER TABLE production_orders ADD COLUMN IF NOT EXISTS cancellation_decided_by UUID REFERENCES users(id);
            END IF;
        END $$
    """))

    # --- tasks ---
    conn.execute(text("""
        DO $$ BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'tasks') THEN
                ALTER TABLE tasks ADD COLUMN IF NOT EXISTS metadata_json JSONB;
            END IF;
        END $$
    """))

    print("INFO: Migration 004 — schema sync complete.")


def downgrade() -> None:
    pass  # columns are additive — not reversing
